In [1]:
#day 1 data science 
pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np # mathematical and numarical operation 

In [3]:
a=10,20,30
print(type(a))  #data type

<class 'tuple'>


In [4]:
b={10,20,30}
print(type(b)) #data type

<class 'set'>


In [7]:
a=np.array(a)
type(a)

numpy.ndarray

In [9]:
b = np.array([[1, 2, 3, 4], [1, 2, 3, 4]])
b

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [15]:
c = np.array([
    [[1, 2, 3, 4], [1, 2, 3, 4]],
    [[1, 2, 3, 4], [1, 2, 3, 4]]
])

print(c)

[[[1 2 3 4]
  [1 2 3 4]]

 [[1 2 3 4]
  [1 2 3 4]]]


In [16]:
np.ndim(c)   #dimension of array [dimension 1,2,3]

3

In [17]:
np.ndim(a)

1

In [19]:
np.ndim(b)

2

In [21]:
np.shape(a)    #coloum ,(row,coloum),(black,cloum,row)



(3,)

In [22]:
np.shape(b)

(2, 4)

In [23]:
np.shape(c)

(2, 2, 4)

In [24]:
np.size(c) #size of array

16

In [25]:
np.size(a)

3

In [26]:
np.size(b)

8

In [2]:
%pip install pillow #image to updateing processer

Note: you may need to restart the kernel to use updated packages.


In [12]:
import numpy as np
from PIL import Image

In [8]:
img=Image.open(r"C:\Users\sumit\Pictures\IMG_20241026_220225.jpg")
img.show()

In [13]:
Image = np.array(img)   #image to connverting a machine processer
Image

array([[[168, 195, 214],
        [170, 197, 216],
        [168, 195, 212],
        ...,
        [125, 160, 190],
        [123, 160, 189],
        [125, 162, 191]],

       [[165, 192, 211],
        [164, 191, 210],
        [165, 192, 211],
        ...,
        [124, 161, 190],
        [125, 162, 191],
        [126, 163, 192]],

       [[163, 190, 211],
        [164, 191, 212],
        [164, 191, 212],
        ...,
        [125, 162, 191],
        [125, 162, 191],
        [125, 162, 191]],

       ...,

       [[ 12,  63,  44],
        [ 19,  70,  51],
        [ 19,  72,  54],
        ...,
        [  2,  10,   0],
        [ 10,  18,   5],
        [ 15,  23,   8]],

       [[  7,  43,  29],
        [ 14,  50,  36],
        [ 16,  52,  38],
        ...,
        [  5,  13,   0],
        [ 20,  28,  15],
        [ 35,  43,  28]],

       [[  2,  28,  17],
        [ 10,  36,  25],
        [ 13,  41,  27],
        ...,
        [ 25,  34,  17],
        [ 43,  51,  36],
        [ 59,  67,  52]]

In [15]:
d=np.arange(1,51)#number to show
d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [16]:
d1=d.astype("float64")  #converting a data type modeling
d1

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
       40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50.])

In [17]:
d=d.reshape(5,10)  #change a reshape of data type or numarical
d

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [18]:
d[::2,::2]   # odd number to print to array model

array([[ 1,  3,  5,  7,  9],
       [21, 23, 25, 27, 29],
       [41, 43, 45, 47, 49]])

In [29]:
#d[0::,0::2] #tow number to next number print it

In [18]:
#vectorixation
def fun(x):
    return x*5
l=[1,2,3,4,5]
m=list(map(fun, l))
print(m)


[5, 10, 15, 20, 25]


In [19]:
#broadcastring
import numpy as np
a=[1,2,3,4,5]
b=[[2],[4],[6]]
print(a)
print(b)

[1, 2, 3, 4, 5]
[[2], [4], [6]]


In [20]:
a=np.array(a)

In [21]:
b=np.array(b) 

In [22]:
c=a+b
c

array([[ 3,  4,  5,  6,  7],
       [ 5,  6,  7,  8,  9],
       [ 7,  8,  9, 10, 11]])

In [25]:
import numpy as np 
m=np.arange(1,51)
m=m.reshape(5,10)
m

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [26]:
m[0::,0::2]#odd number

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49]])

In [27]:
m[m%2==0]#even number

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50])

In [30]:
import numpy as np
a=np.array([[10,20,30],
            [40,50,60]])

In [31]:
#ndim
print(a.ndim)

2


In [33]:
#shape
print(a.shape)#2-rows.3-columns

(2, 3)


In [35]:
#size
print(a.size) #6 elemnts of array 

6


In [36]:
#dtype
print(a.dtype) #show the data type

int32


In [37]:
#arange
a=np.arange(1,11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [40]:
np.arange(2,11,2)

array([ 2,  4,  6,  8, 10])

In [41]:
#astype()
a=np.array([1,2,3,4,5])
b=a.astype(float)
print(b)
print(b.dtype)

[1. 2. 3. 4. 5.]
float64


In [43]:
#linespace
import numpy as np
a=np.linespace(1,10,5)
print(a)

AttributeError: module 'numpy' has no attribute 'linespace'

In [44]:
#idexing get a particular element
a=np.array([10,20,30,40,50])
print(a[0])
print(b[2])

10
3.0


In [45]:
#slicing get a part of an array
a=np.array([10,20,30,40,50])
print(a[1:4])

[20 30 40]


In [46]:
#day 1 class topices
import numpy as np

a = np.array([[10, 20, 30],
              [40, 50, 60]])

print("Array:")
print(a)

print("Dimension:", a.ndim)
print("Shape:", a.shape)
print("Size:", a.size)
print("Data type:", a.dtype)

print("Indexing:", a[0, 1])
print("Slicing:")
print(a[:, 1:])

Array:
[[10 20 30]
 [40 50 60]]
Dimension: 2
Shape: (2, 3)
Size: 6
Data type: int32
Indexing: 20
Slicing:
[[20 30]
 [50 60]]
